services:
  db:
    image: "postgres"
    container_name: "demo-postgres"
    restart: always
    env_file:
      - env
    ports:
      - "54320:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  api:
      build:
          dockerfile: Dockerfile
          context: .
      restart: always
      ports:
          - "8086:8086"
      depends_on:
          - db
      env_file:
          - env
volumes:
  pg_data: