name: Deploy test with trigger

on:
  workflow_dispatch:
    branches:
      - RND/*
    inputs:
      branch-name:
        description: 'The name of the feature branch to deploy'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-name }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: clean test
      - name: Deploy to dev environment
        run: |
          # Replace this with your deployment simulation commands
          echo "Pretending to deploy Java application from branch ${{ github.event.inputs.branch-name }}"
